/*
 * This file is generated by jOOQ.
 */
package org.logiclettuce.database;


import org.logiclettuce.database.tables.FlywaySchemaHistory;
import org.logiclettuce.database.tables.Users;
import org.logiclettuce.database.tables.UsersRoles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.users_roles</code>.
     */
    public static final UsersRoles USERS_ROLES = UsersRoles.USERS_ROLES;
}
