/*
 * This file is generated by jOOQ.
 */
package org.logiclettuce.database.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import org.logiclettuce.database.tables.UsersRoles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRolesRecord extends TableRecordImpl<UsersRolesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users_roles.user_id</code>.
     */
    public UsersRolesRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users_roles.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users_roles.role</code>.
     */
    public UsersRolesRecord setRole(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users_roles.role</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UsersRoles.USERS_ROLES.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UsersRoles.USERS_ROLES.ROLE;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getRole();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getRole();
    }

    @Override
    public UsersRolesRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UsersRolesRecord value2(String value) {
        setRole(value);
        return this;
    }

    @Override
    public UsersRolesRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRolesRecord
     */
    public UsersRolesRecord() {
        super(UsersRoles.USERS_ROLES);
    }

    /**
     * Create a detached, initialised UsersRolesRecord
     */
    public UsersRolesRecord(Long userId, String role) {
        super(UsersRoles.USERS_ROLES);

        setUserId(userId);
        setRole(role);
    }

    /**
     * Create a detached, initialised UsersRolesRecord
     */
    public UsersRolesRecord(org.logiclettuce.database.tables.pojos.UsersRoles value) {
        super(UsersRoles.USERS_ROLES);

        if (value != null) {
            setUserId(value.getUserId());
            setRole(value.getRole());
        }
    }
}
