/*
 * This file is generated by jOOQ.
 */
package org.logiclettuce.database.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.logiclettuce.database.Keys;
import org.logiclettuce.database.Public;
import org.logiclettuce.database.tables.records.UsersRolesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRoles extends TableImpl<UsersRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.users_roles</code>
     */
    public static final UsersRoles USERS_ROLES = new UsersRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRolesRecord> getRecordType() {
        return UsersRolesRecord.class;
    }

    /**
     * The column <code>public.users_roles.user_id</code>.
     */
    public final TableField<UsersRolesRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.users_roles.role</code>.
     */
    public final TableField<UsersRolesRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR, this, "");

    private UsersRoles(Name alias, Table<UsersRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersRoles(Name alias, Table<UsersRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.users_roles</code> table reference
     */
    public UsersRoles(String alias) {
        this(DSL.name(alias), USERS_ROLES);
    }

    /**
     * Create an aliased <code>public.users_roles</code> table reference
     */
    public UsersRoles(Name alias) {
        this(alias, USERS_ROLES);
    }

    /**
     * Create a <code>public.users_roles</code> table reference
     */
    public UsersRoles() {
        this(DSL.name("users_roles"), null);
    }

    public <O extends Record> UsersRoles(Table<O> child, ForeignKey<O, UsersRolesRecord> key) {
        super(child, key, USERS_ROLES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UsersRolesRecord, Long> getIdentity() {
        return (Identity<UsersRolesRecord, Long>) super.getIdentity();
    }

    @Override
    public List<ForeignKey<UsersRolesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USERS_ROLES__USERS_ROLES_USER_ID_FKEY);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.USERS_ROLES__USERS_ROLES_USER_ID_FKEY);

        return _users;
    }

    @Override
    public UsersRoles as(String alias) {
        return new UsersRoles(DSL.name(alias), this);
    }

    @Override
    public UsersRoles as(Name alias) {
        return new UsersRoles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersRoles rename(String name) {
        return new UsersRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersRoles rename(Name name) {
        return new UsersRoles(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
