/*
 * This file is generated by jOOQ.
 */
package org.logiclettuce.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long    id;
    private final String  login;
    private final String  email;
    private final String  password;
    private final Boolean active;

    public Users(Users value) {
        this.id = value.id;
        this.login = value.login;
        this.email = value.email;
        this.password = value.password;
        this.active = value.active;
    }

    public Users(
        Long    id,
        String  login,
        String  email,
        String  password,
        Boolean active
    ) {
        this.id = id;
        this.login = login;
        this.email = email;
        this.password = password;
        this.active = active;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.users.login</code>.
     */
    public String getLogin() {
        return this.login;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>public.users.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(login);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(active);

        sb.append(")");
        return sb.toString();
    }
}
