/*
 * This file is generated by jOOQ.
 */
package org.logiclettuce.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   userId;
    private final String role;

    public UsersRoles(UsersRoles value) {
        this.userId = value.userId;
        this.role = value.role;
    }

    public UsersRoles(
        Long   userId,
        String role
    ) {
        this.userId = userId;
        this.role = role;
    }

    /**
     * Getter for <code>public.users_roles.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.users_roles.role</code>.
     */
    public String getRole() {
        return this.role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsersRoles (");

        sb.append(userId);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
